### ISSUE TITLE
Dwebble has a low quality cry

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#1265]
> BigAngryDev11/19/2020
dwebble's cry is bugged in my repo is it an outdated version or has this bug not been fixed
the source sound is wrong like araquanid's used to be

https://discord.com/channels/419213663107416084/774393519569502268/779046083711336469

**Comment by BuffelSaft** [comment]
The issue here is that Dwebble's cry is very high frequency, so the sample rate of 13379Hz that works for other cries isn't enough for Dwebble's. It needs to be about 26000Hz to avoid losing too much data, but that also means it takes up a lot more space. Better than it sounding as bad as it does though I guess.

I've fixed it in my [resource repo](https://github.com/BuffelSaft/decomp_resources), but haven't got a separate Pokemon expansion branch setup to create a pull request for it.

**Comment by LOuroboros** [comment]
No longer relevant.
