### ISSUE TITLE
Move data error: MOVE_SMELLING_SALTS is named "SmellngSalts" instead of "SmellingSalt" 

### ISSUE THREAD

**Issue by pineapplemachine** [rh-hideout/pokeemerald-expansion#1495]
The error is in `pokeemerald-expansion/src/data/text/move_names.h` on line 268:

``` c
    [MOVE_SMELLING_SALTS] = _("SmellngSalts"),
```

This is a move introduced in generation 3 as `SmellingSalt` and later renamed to `Smelling Salts` in generation 6.

This project changes the name of the move to `SmellngSalts` instead, which I believe is in error.

https://bulbapedia.bulbagarden.net/wiki/Smelling_Salts_(move)

**Comment by LOuroboros** [comment]
> 
> 
> The error is in `pokeemerald-expansion/src/data/text/move_names.h` on line 268:
> 
> ```c
>     [MOVE_SMELLING_SALTS] = _("SmellngSalts"),
> ```
> 
> This is a move introduced in generation 3 as `SmellingSalt` and later renamed to `Smelling Salts` in generation 6.
> 
> This project changes the name of the move to `SmellngSalts` instead, which I believe is in error.
> 
> https://bulbapedia.bulbagarden.net/wiki/Smelling_Salts_(move)

It's not an error. Due to the limit of characters in ability and move names, a naming convention inspired by the MegaMan Battle Network games was adopted, hence why instead of "Smelling Salts" which is 14 characters long, it was decided to use "SmellngSalts" instead. Sounds the same, conveys the move's full name and complies with the character limit.

Of course, you're free to change this sort of things in your own projects.
