### ISSUE TITLE
Shroomish's backsprite has him levitating

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#1496]
Title
![image](https://user-images.githubusercontent.com/2904965/119052256-535e8800-b992-11eb-9fa2-f99ac9bdac39.png)

**Comment by Blackforest92** [comment]
The levitating part is because of the spriter using HGSS's official sprite.
It looks weird for me as well, cutting 4 pixels from below should fix it.
However,
I think everyone need to decide if the fix is necessary since this is taken from official sprite.

Comparison :
HGSS : https://img.pokemondb.net/sprites/heartgold-soulsilver/back-normal/shroomish.png
DP : https://img.pokemondb.net/sprites/diamond-pearl/back-normal/shroomish.png

**Comment by LOuroboros** [comment]
> 
> 
> The levitating part is because of the spriter using HGSS's official sprite.
> It looks weird for me as well, cutting 4 pixels from below should fix it.
> However,
> I think everyone need to decide if the fix is necessary since this is taken from official sprite.
> 
> Comparison :
> HGSS : https://img.pokemondb.net/sprites/heartgold-soulsilver/back-normal/shroomish.png
> DP : https://img.pokemondb.net/sprites/diamond-pearl/back-normal/shroomish.png

There's no need to cut anything at all. Increasing the value of Shroomish's back sprite's Y coord by 1 or 2 in `src/data/pokemon_graphics/back_pic_coordinates.h` should be more than enough.

**Comment by Blackforest92** [comment]
> Increasing the value of Shroomish's back sprite's Y coord by 1 or 2

The rest of the sprites in our repo are all matching with their data in `src/data/pokemon_graphics/back_pic_coordinates.h`.
Beside all i need to do is adjusting the position of the graphic and port the `shiny.pal` into it.
At the same time, pushing a fix to [#1488 ](https://github.com/rh-hideout/pokeemerald-expansion/issues/1488) and graphical glitch of Xerneas Active as well.

**Comment by LOuroboros** [comment]
> 
> 
> > Increasing the value of Shroomish's back sprite's Y coord by 1 or 2
> 
> The rest of the sprites in our repo are all matching with their data in `src/data/pokemon_graphics/back_pic_coordinates.h`.

I'm not sure what do you mean by that. The coordinates are normally set based on the sprite, so it can be properly positioned on the screen and so you won't have to fiddle with the sprite itself pointlessly.

I mean, that's normally what I used to do to fix the position of a sprite in battle. Leave the sprite alone and tweak its Y position as needed. I thought that was par for the course.

**Comment by Blackforest92** [comment]
> I'm not sure what do you mean by that.

While your solution does solve the problem, i just feel that since the all pokemon graphic (.png files) in our repo are matching with the Y coordinate code. It just kinda feel wrong to add 2 - 4 points to into [Shroomish's Y position](https://github.com/rh-hideout/pokeemerald-expansion/blob/02c20c0737b8fabb6bbbbe234233e4be9c3d1060/src/data/pokemon_graphics/back_pic_coordinates.h#L1411) while its graphic is 9px counted up from below, which is currently matching with its code.
I just want the graphic file to match the code.

Nevertheless, both solutions work. Either just push fix to the one `.png` or edit the Y position.
Both are 30secs fixes.

**Comment by DizzyEggg** [comment]
#1513
