### ISSUE TITLE
Mega forms and Alternate forms do not have weight since they aren't in the dex

### ISSUE THREAD

**Issue by Ryuhouji** [rh-hideout/pokeemerald-expansion#1547]
This causes moves like heavy slam, low kick, and grass knot to malfunction when used against these mons in battle. The game gets the `.weight` field from the pokedex entries. If a mon does not have a dex entry (or if someone is doing a project that only features some generations) then the moves will not work.

**Comment by DizzyEggg** [comment]
This doesn't happen atm, because the GetBattlerWeight function uses SpeciesToNationalPokedexNum which has all of the forms/megas covered.

https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/src/battle_util.c#L8341
https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/src/pokemon.c#L1257
