### ISSUE TITLE
Trick needs to be updated to its modern effect

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1658]
Currently, Trick and Switcheroo have the following issues:
- Items Tricked onto a trainer's Pokémon are lost forever. In modern games they're restored at the end of the battle.
- Trick works on Mega Stones (or at least it appears to - could just be the wrong string being printed). It should fail when used against a Pokémon that can't lose its item.

**Comment by AsparagusEduardo** [comment]
I can't reproduce either of these scenarios. It might've been fixed in #1221 .
> Items Tricked onto a trainer's Pokémon are lost forever. In modern games they're restored at the end of the battle.

![megatrick](https://user-images.githubusercontent.com/2904965/135679498-3582f0b3-59fb-40bc-b465-7ae2b404b29a.gif)

> Trick works on Mega Stones (or at least it appears to - could just be the wrong string being printed). It should fail when used against a Pokémon that can't lose its item.

![megatrick](https://user-images.githubusercontent.com/2904965/135679139-c5ba3599-e503-47e5-9e28-94ae11f3296b.gif)

**Comment by BuffelSaft** [comment]
> I can't reproduce either of these scenarios. It might've been fixed in #1221 .
Seems like it! Will close this issue.
