### ISSUE TITLE
Moxie doesn't activate if the user's spread move KO's a diagonally-opposite target

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1717]
Sorry for the stupid title, this one's hard to explain concisely.

Example: Player is in a double battle with a Moxie Honchkrow on the right and some other mon on the left. The foe on the right side of the screen has already fainted this turn. Honchkrow uses Heat Wave and this KO's the foe on the left side of the screen, but Moxie doesn't activate.

If a single target move KO's a foe in that position Moxie will activate as usual, seems it's just multi target moves that have this problem.

Noticed this in my hack but haven't confirmed in the BE yet.

**Comment by kleeenexfeu** [comment]
To be more precise, gBattleStruct->moveTarget[gBattlerAttacker] isn't updated on the second (and possibly 3rd if the move targets the whole field?) hit of a spread move.
So when calling src/battle_script_commands.c/HasAttackerFaintedTarget  this is checked :

gBattleStruct->moveTarget[gBattlerAttacker] == gBattlerTarget

and the engine believes that our mon hasn't koed the target, because the condition above isn't true

The same issue happens with follow me/moxie in double battle:

Moxie Gyarados waterfall Opposing Rhydon
Opposing Pachirisu used follow me
Moxie Gyarados Koes Pachirisu
Moxie DOESN'T activate.

In this case, I believe src/battle_util.c/HandleAction_UseMove doesn't do it's job with the follow me target, and again doesn't update gBattleStruct->moveTarget[gBattlerAttacker] properly in all cases.

I haven't fixed it myself, because despite discussing this with ghoulash on discord, I'm still not sure yet how to tackle the problem.

**Comment by ghoulslash** [comment]
#1976
