### ISSUE TITLE
Slight pixel error with Fairy type icon

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#1792]
Reported by PHX#8049 on PokeCommunity's discord.
Mainly the shadow in the I, but maybe we could consider updating the shadow bottom of the icon, as I also agree that the icon does look a bit off compared to the other ones.

![image](https://user-images.githubusercontent.com/2904965/138002837-1a3da379-7b38-4f1a-98de-3e0b9a1eac01.png)

**Comment by LOuroboros** [comment]
I don't understand what he said.
The shadow on the type sprites' letters, from what I was able to understand back when I made the sprite, is supposed to incline towards the east, that's why there isn't a pixel for shadow inbetween the "A" and "I".
Putting one there also makes the sprite look ugly, although that's more of a subjective matter.

The bottom left of the type sprite is correct. The Dragon type sprite's is the one that is not, but as they said, it's a vanilla thing.
All in all, there's no reason not to "fix" it and throw in a pixel in there to make it consistent with the other type sprites.

The only thing I can effectively agree with is that the colors suck.
I'm guessing we may be able to add a 4th type sprite palette and make the Fairy type use it? It'll need some looking into.

**Comment by AsparagusEduardo** [comment]
> I don't understand what he said. The shadow on the type sprites' letters, from what I was able to understand back when I made the sprite, is supposed to incline towards the east, that's why there isn't a pixel for shadow inbetween the "A" and "I". Putting one there also makes the sprite look ugly, although that's more of a subjective matter.

Seeing as there's a shadow pixel underneath the first column in the Y, it does make sense for there being a shadow pixel underneath the first column of the I

> The bottom left of the type sprite is correct. The Dragon type sprite's is the one that is not, but as they said, it's a vanilla thing. All in all, there's no reason not to "fix" it and throw in a pixel in there to make it consistent with the other type sprites.

I don't know why I also pasted the Dragon part, I don't actually think that should be fixed.

> I can effectively agree in that the colors suck though. I'm guessing we may be able to add a 4th type sprite palette and make the Fairy type use it? It'll need some looking into.

Maybe we should also check if there are other available colors we could use for it. Maybe Psychic's or Poison's?

**Comment by LOuroboros** [comment]
> Seeing as there's a shadow pixel underneath the first column in the Y, it does make sense for there being a shadow pixel underneath the first column of the I

OH. Alright.
I was thinking about the space inbetween the shadow pixel of the "A" and the beginning of the "I".
Yeah, I agree. There should definitely be a shadow pixel underneath the upper part of the "I".

> Maybe we should also check if there are other available colors we could use for it. Maybe Psychic's or Poison's?

I don't think so. I already used the colors of those types.
More specifically, the sprite uses the 2nd out of the 3 palettes for type sprites which was the only one that has colors befitting the Fairy type's sprite, based on its color scheme in the official games *(pink)*.
![gale_1786](https://user-images.githubusercontent.com/4485172/140518542-171841fc-b23a-47bd-b06a-114b9ac4aa48.png)

I think we really need a 4th palette if we want to have a Fairy type sprite with nice colors, or nicer than the ones the current one uses :eyes:

I looked at it super quickly yesterday, but I didn't have much luck.
![](https://media.discordapp.net/attachments/774393519569502268/905976449377382481/mGBA_1785.png)
https://github.com/LOuroboros/pokeemerald/commit/4f655842de1bd525ef80496b9d8117d2d0c42db6
