### ISSUE TITLE
Quash might be broken

### ISSUE THREAD

**Issue by BuffelSaft** [rh-hideout/pokeemerald-expansion#1803]
This is another bug reported in my hack and not confirmed in the BE yet. Apparently Quash not only doesn't make the target move last, it makes the target move twice in the same turn. I suspect that it moves the target's action to the end of the move/turn order, but doesn't remove its initial action somehow.

**Comment by LOuroboros** [comment]
There's 2 small issues related to this one. The battle string for Quash lacks a line break, and it uses the wrong battler too.
Also, it seems that the reason why the targetted battler moves twice is because it's stealing another battler's turn?
I had my Poochyena use Tackle, but it never happened. I feel that either of the 2 times Seedot used Harden, my Poochyena should have used their move instead.
![%pn_1781](https://user-images.githubusercontent.com/4485172/140419197-54e948c5-4ca5-4a33-9625-b71a5aab54fa.gif)

**Comment by kleeenexfeu** [comment]
This is fixed in https://github.com/rh-hideout/pokeemerald-expansion/pull/1974
