### ISSUE TITLE
Moves that hit multiple targets canceled by Desolate Land or Primordial Sea show its message multiple times

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#1806]
Lava Plume
![lavaplume](https://user-images.githubusercontent.com/2904965/138537030-8a9c430d-1f60-461b-bc94-557bf060a1f8.gif)
Surf
![surfinusa](https://user-images.githubusercontent.com/2904965/138537031-80ef0162-26c3-47e2-bf0c-7d26ded27c55.gif)
Heat Wave
![waveofheat](https://user-images.githubusercontent.com/2904965/138537032-6313a658-1568-485a-9e49-21dadf55c2df.gif)

**Comment by kleeenexfeu** [comment]
Could also be because of [this line of code](https://github.com/rh-hideout/pokeemerald-expansion/blob/battle_engine/src/battle_script_commands.c#L1381), the current battlescript is pushed, to be popped later. So the move tries to hit 3 times. If it's entirely replaced by the primal weather messages, it won't try to hit several times.
Haven't tested yet, I'll update when I do (or remove this comment if I'm wrong).

**Comment by LOuroboros** [comment]
#1861
