### ISSUE TITLE
AI Lag

### ISSUE THREAD

**Issue by ghoulslash** [rh-hideout/pokeemerald-expansion#1944]
This has been reported by several users, but a specific commit has yet to be identified as the culprit. It is particularly noticeable in double battles.

**Comment by Skeli789** [comment]
I have three guesses as to what is causing the lag:
1. The switch logic.
2. The damage calcs.
3. The item usage logic, but there really shouldn't be a reason this would take a long time unless something got badly messed up.

If it turns out it's because of the damage calcs, as your AI gets smarter, this is going to happen - a smarter AI needs better calcs, after all. If you'd prefer no lag over smarter AI, you could reduce the number of damage calcs the AI does. But if you do want to keep the smart AI, I recommend doing two things:
- Wipe the textbox at the end of each turn. This allows for a more seamless transition between the end of the turn and before the player can choose an action (it's a similar fix with how Link Battles print the string "Communicating, please stand by...").
- Cache your damage calcs. There's no reason the AI should ever perform a damage calc on a specific target more than once (unless you want the second AI mon to factor in the move the first AI mon chose - eg. for a move like Assurance).

**Comment by kleeenexfeu** [comment]
After a little bit of debugging, here his what I've got :
AI_CheckViability is easily to most consuming function and it's called many times.
AI_TryToFaint is number two.
These two functions are head and shoulders above the rest in terms of cycles.
They use about 1M cycles every time they are called by BattleAI_DoAIProcessing.
With AI_CheckViability being the number1 reaching more than 3M cycles several times.

I don't know yet if the lack of optimization come from the functions themselves, or if we'd just have to dump a bunch more results in the RAM to avoid constant recalculation -or both.
I'll update this post as I make progress; if I make any!

**Comment by kleeenexfeu** [comment]
Seems to have improved a lot since https://github.com/rh-hideout/pokeemerald-expansion/commit/14f974c9a95fe9801a744955973303b242036a11

**Comment by ghoulslash** [comment]
#1954
