### ISSUE TITLE
Some species can learn TMs/HMs they're not supposed to be able to

### ISSUE THREAD

**Issue by LOuroboros** [rh-hideout/pokeemerald-expansion#2094]
Title. Originally found by Discord user Garfielle#7229, and I confirmed it on the Master branch as well.

I suppose it's coming from the item_expansion after the TM related changes in #1561 to functions such as `CanMonLearnTMTutor`.

![](https://media.discordapp.net/attachments/774393519569502268/965228729955651644/notepad_17042022_0932719.png?width=922&height=505)

**Comment by AsparagusEduardo** [comment]
#2095

**Comment by redthing1** [comment]
Wondering if this is related? https://github.com/rh-hideout/pokeemerald-expansion/blob/item_expansion/src/data/pokemon/tmhm_learnsets.h#L2

**Comment by TristanaGW** [comment]
I don't know if this is already known, but I want to have it stated explicitly for people who want to investigate (and because I'm still not familiar enough with the structure of the code to fix it myself), the symptom of the problem is that Pokémon are able to learn the HMs that correlate to the TMs of the same number that they can learn.
Examples - Abra can learn Cut (HM01), when it shouldn't be able to, because it learns Focus Punch (TM01). Poochyena can learn Flash (HM05), when it shouldn't be able to, because it learns Roar (TM05).

**Comment by PeppaPigHS** [comment]
Should be from how HM indices are calculated differently between ```tmhm_learnsets.h``` in ```item_expansion```, and ```party_menu.c``` in ```master``` (https://github.com/rh-hideout/pokeemerald-expansion/blob/item_expansion/src/data/pokemon/tmhm_learnsets.h#L2, https://github.com/rh-hideout/pokeemerald-expansion/blob/master/src/party_menu.c#L1967).

**Comment by TristanaGW** [comment]
That's the fix to go for as a holdover for now I think. That or just reverting `NUM_TECHNICAL_MACHINES` back to `50` fixes everything to how it should be, but only by consequence of now treating HMs 01-08 as TMs 51-58 rather than TMs 01-08, as evidenced by adding `TM_55` to Combusken's learnset allowing it to learn `HM_05` after the fix. (So Peppa's fix of changing it in the ternary to 50 is technically the more accurate fix.) I think there might be a lot of code that doesn't account for unused TM IDs too.
At the moment, there's only room to formally fit 64 TMs/HMs because of the code using two u32 bit arrays. This also means that inserting a TM value above 64 anyways just doesn't work to begin with without any fixes. I'm not familiar enough with C yet to work out a fix myself just yet, but the learnsets need to be expanded to at least four bit arrays to fit the 108 TMs/HMs (and a max of 128) the project is looking for at the moment. This might be able to be done dynamically, but frankly I have no idea.

**Comment by LOuroboros** [comment]
#2166
