### ISSUE TITLE
Add support for multi battles with a singular wild opponent

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#2103]
```
        setwildbattle(SPECIES_EXCADRILL,100,ITEM_MUSCLE_BAND)
        playmoncry(SPECIES_EXCADRILL,CRY_MODE_ENCOUNTER)
        msgbox("roar",MSGBOX_AUTOCLOSE)
        delay(40)
        waitmoncry
        multi_fixed_wild(TRAINER_WALLY_VR_2,TRAINER_BACK_PIC_WALLY)
```

![image](https://user-images.githubusercontent.com/77138753/165225774-78f21c90-cd55-498c-aa8f-590bcfe8d97e.png)

I'm trying to create a boss battle where the player and a rival battle against a very strong wild Pokemon. 

When I only pass one argument to `setwildbattle`, I get MissingNo and the Excadrill. I've been told this is a limitation of the current state of affairs and would require a non-zero amount of work to support.

**Comment by LOuroboros** [comment]
> ```
>         setwildbattle(SPECIES_EXCADRILL,100,ITEM_MUSCLE_BAND)
> ```

[`setwildbattle` has been modified 2 years ago](https://github.com/rh-hideout/pokeemerald-expansion/commit/151aca83650fb37dc889b08fdca990f3939ec549) to accept a 2nd set of species, level and item, exactly so it could be used to prepare scripted double wild battles.

https://github.com/rh-hideout/pokeemerald-expansion/blob/battle_engine/src/scrcmd.c#L1878-L1880

Something like this should work:
```
        setwildbattle(SPECIES_EXCADRILL,100,ITEM_MUSCLE_BAND,SPECIES_EXCADRILL,100,ITEM_MUSCLE_BAND)
        playmoncry(SPECIES_EXCADRILL,CRY_MODE_ENCOUNTER)
        msgbox("roar",MSGBOX_AUTOCLOSE)
        delay(40)
        waitmoncry
        dowildbattle
```

Since this feature request is not really valid, I'll proceed to close this Issue ticket.
