### ISSUE TITLE
Reminder: See if Quash's effect changes with B_RECALC_TURN_AFTER_ACTIONS

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#2276]
To see if we mark that item in #1401

**Comment by DizzyEggg** [comment]
I assume we can mark that item as done and close this issue now?
https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/src/battle_util.c#L950

**Comment by AsparagusEduardo** [comment]
I don't know, was it tested? 👀

**Comment by AlexOn1ine** [comment]
what exactly needs to be tested?

**Comment by kleeenexfeu** [comment]
Pretty sure the problem is this code :
                if (gProtectStructs[battler1].quash || gProtectStructs[battler2].quash
                    || gProtectStructs[battler1].shellTrap || gProtectStructs[battler2].shellTrap)
                    continue;
                    
   You can fin it here : https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/src/battle_util.c#L878-L880
   
   But if in the meantime the code changes:              
  It's in src/battle_util.c/HandleAction_ActionFinished
  If one mon is quashed, the order isn't recalculated, which should be the whole point of this status.
