### ISSUE TITLE
AI withdrawing behaviour w/o damage move, Pokemon-to-switch and next-Pokemon-sendin decisions

### ISSUE THREAD

**Issue by StubbornOne** [rh-hideout/pokeemerald-expansion#2320]
Hi, not a bug(?) but may be of interest for the AI.

On the master branch (17fecd5), I modded Winona1's team to the following:
1. Skarmory with {MOVE_SPIKES, MOVE_TOXIC, MOVE_WHIRLWIND, MOVE_ROOST}
2. Tropius with {MOVE_LEAF_TORNADO, MOVE_BODY_SLAM, MOVE_PROTECT, MOVE_ROOST}
3. Hawlucha with {MOVE_SUPERPOWER, MOVE_ACROBATICS, MOVE_U_TURN, MOVE_ROOST}
4. Mantine with {MOVE_CONFUSE_RAY, MOVE_WATER_PULSE, MOVE_AIR_SLASH, MOVE_ROOST}
5. Altaria with {MOVE_DRAGON_PULSE, MOVE_TOXIC, MOVE_COTTON_GUARD, MOVE_ROOST}

Winona1 has the default aiFlags AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_TRY_TO_FAINT | AI_FLAG_CHECK_VIABILITY | AI_FLAG_RISKY

Put Winona in InsideOfTruck, and something to "givemon SPECIES_RAICHU_ALOLAN, 50, ITEM_ZAP_PLATE" to the player (Raichu gets Thundershock, Tail Whip, Quick Attack and Thunderbolt), to battle immediately in a new game:

![skarmorywithdraw](https://user-images.githubusercontent.com/81517503/190185181-8f23a841-398b-454f-9abc-81aba5f35e09.gif)

1. Winona switches Skarmory into Hawlucha (only one with supereff move, but is not necessarily faster + has been consistently OHKOed by Tbolt upon switchin), then Mantine (?), then Altaria then Tropius
2. Winona sends in Skarmory again (?) after the current Pokemon faints, then withdraws in the above order
3. If I replace Hawlucha's U-turn with Brick Break, Winona withdraws Skarmory into Mantine first, then Hawlucha
4. If I put Hawlucha (with U-turn) at the front and ensure it outspeeds Raichu, Hawlucha uses Superpower instead
5. If I give Skarmory Razor Wind (replacing Whirlwind), Winona does not switch Skarmory who then gets knocked out
6. If I replace Skarmory with an outspeeding Crobat with *Parting Shot*, Whirlwind, Toxic, Roost; Winona *withdraws* Crobat into Hawlucha
6a. If the Crobat has U-turn, Whirlwind, Toxic, Roost; Crobat stays and uses Toxic

If I'm not wrong:
-Switching doesn't account for the incoming Pokemon's survivability
-Switching factors in supereff of moves, but not other effects/damage/? factored by the aiFlags
-Switching is stopped by the presence of a damage move, even if the move can't get off/isn't effective/isn't picked
-Not sure about the Mantine priority (confusion? flinch?)
-Not sure about the Skarmory re-sendin
-EFFECT_HIT moves seem discouraged?

Sorry if this isn't appropriate as an issue

**Comment by Porygon23** [comment]
Hey! The switching AI is still in it's infancy, with limited work that has been done so far above what the base battle engine supports. But I can answer a few of these questions to try to clear up what has been done and what has not.

Most of the logic that you are after can be found in `GetMostSuitableMonToSwitchInto`. This function is called when the decision to switch is True, or after a pokemon is knocked out. It's also starting to get used in some switching logic, to determine if there is actually a favorable mon existing in the party, or if its better to just stay in the battle.
Note: If no favorable mon is found from this function, the decision of what to send out relies on party order.

> Switching doesn't account for the incoming Pokemon's survivability
> Switching factors in supereff of moves, but not other effects/damage/? factored by the aiFlags
These are true currently. Basically, the logic of which mon to switch too checks the following:
1. Find best mon for baton pass (if baton pass is the reason for switching)
2. Find mon that is suited defensibly (effectiveness less than nuetral) & has a super effective move against players pokemon. 
3. Find mon that deals the most damage, by move base power.

`Switching is stopped by the presence of a damage move, even if the move can't get off/isn't effective/isn't picked`
This is true to some sense. The Switching function `ShouldSwitchIfAllBadMoves` is more likely to trigger if all of the active pokemons moves are power 0. Which is the case for the skarmory above. This will need to be fixed in the battle engine, since toxic is a move with power 0, but is a valid "damaging move".

> Not sure about the Mantine priority (confusion? flinch?)
I'm not 100% sure on this reasoning. It might be because after the switch from Skarmory to Hawlucha, then maybe Skarmory is registered as party slot 3, so Mantine is the next party slot if no favorable mon is found (see above).

> Not sure about the Skarmory re-sendin
I belive this is happening because the AI cannot find a good defensive mon with a super effective move (see above), so it is defaulting to party order...

> EFFECT_HIT moves seem discouraged?
Not neccassarily discouraged, but simply that the move decision process & switchin logic is seperate currently. Eventually, logic will need to be added to enable a switching attack instead, if the decision to switch has already been made & the pokemon is faster.


I believe this issue should be left open until all the issues above can be addressed. This issue ticket will provide a sort of log and roadmap of things that need to be completed for AI Switching Logic.
I'll work on fixing these issues right away.

**Comment by StubbornOne** [comment]
Thanks for your help!

**Comment by LOuroboros** [comment]
#3146
