### ISSUE TITLE
Light That Burns The Sky's name doesn't display fully in battle box 

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#2351]
![image](https://user-images.githubusercontent.com/2904965/192097139-732412d2-ba2e-4c68-aa02-0e23a5730130.png)

**Comment by Jaizu** [comment]
I think this is fine but we have to be way more careful about text-windows in the future. The ideal solution should be to add a new window called zmovesmovename that uses the same with as move name 1 + move name 2.
To make it more clear, you made the text-window larger but you didnt make the next text windows start on a later baseblock.
Atm it's 12 * 2 = 24 = 0x18 in hex. Current baseblock is 0x300, move name 2 baseclock is 0x318.
To make this correct, we should make the next baseblock have a higher value, including all the other windows that start after that baseblock, otherwise we might overwrite windows in the vram.
