### ISSUE TITLE
Pyroar Female Back sprite...

### ISSUE THREAD

**Issue by Meister-anon** [rh-hideout/pokeemerald-expansion#2547]
Pyroar  backf.png just looks bad, if I had the ability I'd submit something better.

But my recommendation is to do something more similar to the back sprite for
galarian rapidash more flowing mane, instead of a tube...

**Comment by AsparagusEduardo** [comment]
It is a tube though :thinking: 
![backf](https://user-images.githubusercontent.com/2904965/210156239-089a3755-34e8-4c58-b42b-37b060aad7aa.png)
![image](https://user-images.githubusercontent.com/2904965/210156262-2a233fe2-aa5d-4d8f-8648-5b4cb8033df2.png)

**Comment by Meister-anon** [comment]
That's a bad sprite, its supposed to be a mane of fire not a tube.

![image](https://user-images.githubusercontent.com/78051659/210160662-836e944b-d577-4806-a361-af81ea6a72db.png)

**Comment by Meister-anon** [comment]
Like this looks great, it flows, it looks graceful, very well done.

![back](https://user-images.githubusercontent.com/78051659/210160736-c2a1333d-734d-4b94-8e1f-7d424d94de0c.png)

**Comment by BuffelSaft** [comment]
The design itself is bad, it's genuinely supposed to be a tube made of hair/fur. It's not fire, as can be seen in game and in the official art; those glossy patches wouldn't be there if that was fire.

**Comment by AsparagusEduardo** [comment]
Whatever it's fire or hair, the official design makes it look like a tube and the back sprite captures that. From each of the sprite sources that we use have it like that/use the same backsprite.
<https://www.pokecommunity.com/showthread.php?t=336945>
<https://www.pokecommunity.com/showthread.php?t=314422>
<https://github.com/Skeli789/Dynamic-Pokemon-Expansion/blob/Unbound/graphics/backspr/gBackShinySprite831PyroarFemale.png>

This issue seems to be more of a "Female Pyroar's hair looks bad" instead of a "this sprite isn't very representative of the official look for the species", which would be within the expansion's scope. I feel that the back-sprite does a good job at showing what Female Pyroar look from behind. We're open to sprite submissions for improvements, but as it stands, I don't think this needs an active issue, so I'm going to close it for now.

**Comment by Meister-anon** [comment]
bro it looks awful, even the original pokemon team goes and revamps sprites/models that look bad.
There's no reason to stick with a bad design just because you were attempting to emulate a bad official model.

I'm only putting so much emphasis on ya'll doing it, because you're the biggest group and going forward
yours is the base everyone will use, and ya'll clearly have the ability to make/get made better sprites as you have done better than this.

If the argument to follow the spirit of the design  for the sake of the visual doesn't move you,
then what about quality control?
Every other sprite looks good/great but this sticks out like a sore thumb because it doesn't match the same level of quality.

**Comment by AsparagusEduardo** [comment]
If you find a source for a better back sprite, please post it here so we can review it and apply it.
