### ISSUE TITLE
Tests for Move Animations

### ISSUE THREAD

**Issue by DizzyEggg** [rh-hideout/pokeemerald-expansion#2788]
With the recent #2784 issue and similar ones in the past, it would be a good idea to have some automatic tests for move animation.
Obviously checking graphical glitches would be hard, but catching things like softlbocks/crashes and similar should be doable.

**Comment by Jaizu** [comment]
We could use some timers to check if something softlocked

**Comment by AsparagusEduardo** [comment]
Couldn't those be handled by the existing battle tests?

**Comment by mrgriffin** [comment]
I think this is a good idea. Softlocks and some crashes are already converted into `TIMEOUT` failures by the test runner. Detecting a crash that resets the game is more difficult, but might be possible with some additions to `crt0.s` (at any rate, it'll be obvious because the tests will never terminate :sweat_smile:). You may also be able to detect other errors by checking that all the battler's sprites are visible by the end of the animation, don't have affine matrices associated with them, etc.

Regarding using the battle tests, it's definitely an option. The only drawback I can think of is that the tests will not run as fast as tests that avoid actually running all the battle logic. It's probably worth prototyping via battle tests and then if that's too slow we can look at writing a test runner specifically for battle animations :)

**Comment by Bassoonian** [comment]
Superseded by #4932
