### ISSUE TITLE
Strange stat drops happen when a mon disobeys

### ISSUE THREAD

**Issue by SubzeroEclipse** [rh-hideout/pokeemerald-expansion#2853]
I found out that when a Pokémon disobeys the Player, if attempting to use a move that drops the user's stats, the enemy may get the drops that were supposed to be caused by that move. For example, in this gif Sceptile was about to use Leaf Storm and then the enemy Zigzagoon got the -2 Special Attack drop after using Tackle.
![leaf-storm2](https://user-images.githubusercontent.com/115349505/227019795-18949b21-dd56-4271-8771-73e10be25eeb.gif)
And also, the user may get those drops too when uses another move as an effect of the disobedience:
![leaf-storm1](https://user-images.githubusercontent.com/115349505/227021108-6c75b706-b5f6-4f5d-ad01-e83ca3f4147e.gif)
From what I can see, this only happens with moves that drop stats: I couldn't reproduce it when using moves that raise stats, or any other effect.

**Comment by cfmnephrite** [comment]
So the problem is caused the stat drops from Leaf Storm being added to gBattleScripting.statChanger _before_ the move is cancelled by disobedience. This value persists until the next move which is why Zigzagoon's Tackle reads it and executes it. The easy fix is just to have statChanger set to 0 at the end of cmd_moveend. Is there any reason _not_ to implement that?

**Comment by DizzyEggg** [comment]
That's a pretty interesting bug, I wonder if it occurs in vanilla emerald too.
