### ISSUE TITLE
Using items in battles feel weird due to the item battle scripts rework

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#2912]
A few things are wrong:
- It says that you used the potion in the party menu and the hp doesnt heal
- It says that you used the potion again in battle
- It says that HP was restored before having them restored

![mGBA_G08FnZeLvd](https://user-images.githubusercontent.com/18596778/232225037-39e553a4-45a9-4fe5-a98c-5cc711515922.gif)

Feels like this should have been tested more, something basic like using a potion shouldn't be broken on such a big PR.

**Comment by AgustinGDLV** [comment]
This was all intended and visible on the original PR showcases, minus the heal string printing after healing is done. The party use message is there for items that won’t have any effect, but I can turn it off otherwise. It’s nice to have it in a double battle because you will not go straight to item execution after using the item.

**Comment by AsparagusEduardo** [comment]
Fixed by #2915
