### ISSUE TITLE
AI scoring with flame charge vs a Pignite

### ISSUE THREAD

**Issue by Jaizu** [rh-hideout/pokeemerald-expansion#2944]
![image](https://user-images.githubusercontent.com/18596778/233829569-41f2256b-8fa5-4903-b3ae-bbeb66c0afec.png)

mon data
```
    {
    .iv = 250,
    .lvl = 24,
    .species = SPECIES_ZEBSTRIKA,
    .heldItem = ITEM_SITRUS_BERRY,
    .moves = {MOVE_QUICK_ATTACK, MOVE_SHOCK_WAVE, MOVE_VOLT_SWITCH, MOVE_FLAME_CHARGE},
    }
```

**Comment by AlexOn1ine** [comment]
I guess the tester didn't have the debug menu to check the scores? Would be helpful for debugging.

**Comment by Jaizu** [comment]
No, he was a regular user, so no debug menu.
And Shock Wave and/or Volt Switch should have more prio than flame charge vs a fire mon in every scenario, probably the flame charge stats boost fucking around, idk

**Comment by AlexOn1ine** [comment]
> And Shock Wave and/or Volt Switch should have more prio than flame charge vs a fire mon in every scenario, probably the flame charge stats boost fucking around, idk

I edited the comment above to include this:
```

To clarify. If the highest damage dealing move is discouraged (for whatever reason) the AI starts using random moves. This is vanilla behavior in all Pokemon mainline games
```

**Comment by AlexOn1ine** [comment]
Though I do think that `Volt Switch` could be handled better in that case. It shouldn't be discouraged if it is the last mon.

**Comment by Jaizu** [comment]
I don't think Volt Switch is the main problem here, that mon also has Shock Wave, so I'm not buying that
Like, in which scenario should pref:
Fire type move without stab vs fire Pokémon
VS
Elec type move with stab vs non elec Pokémon

I think the stat boost is broken or maybe the ai just prefs volt switch over shock wave and the disregards it. I honestly have no clue, but I think it's very odd that this scenario happens.

**Comment by AlexOn1ine** [comment]
I don't disagree. Things can be be improved for sure. The problem is that not matter how much things you are trying to cover sometimes the AI will do stupid things. In that case improving move sets can go a long way. For example if you give `Zebstrike` Thunderbolt instead of Shock Wave the scoring already improves. 
![pokeemerald-1](https://user-images.githubusercontent.com/93446519/233834015-0cb20350-c412-45a3-b00d-3844bb7acbcc.png)
![pokeemerald-0](https://user-images.githubusercontent.com/93446519/233834018-7195789f-61ec-4011-93ad-03edbd14dd35.png)
