### ISSUE TITLE
Flag debug screen corrupts subsequent message boxes

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#3173]
### Description

Navigating to the flag section of the debug menu before trying to save the game will mess up the windows of the save window message box. It will also make any subsequent messagebox in the OW invisible (since it doesn't have the save data box to resort to).

![debugsaveissue](https://github.com/rh-hideout/pokeemerald-expansion/assets/16993385/06fb0b30-a9e6-4f4a-a26e-70c06fb48ecc)

### Version

upcoming (Edge)

### Discord contact info

bassoonian

**Comment by pkmnsnfrn** [comment]
I have repro as of d143d508e0a334cf172f593d9e970e34990a3de5

You can tell that I'm talking to Nurse Joy after using the Flags because

1. The Yes/No box pops up 
2. Overworld objects all freeze up
3. Nurse Joy bows after healing

https://github.com/rh-hideout/pokeemerald-expansion/assets/77138753/3b71d43b-86fe-4e78-b9b8-b9cdd67e3917

**Comment by AsparagusEduardo** [comment]
#3317
