### ISSUE TITLE
Held Item Metronome does not work as intended

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#3244]
### Description

The Held Item Metronome does not work as intended and instead seems to significantly lower damage output.
https://discord.com/channels/419213663107416084/774393519569502268/1143185746761617590

### Version

1.5.2 (Default)

### Discord contact info

bassoonian

**Comment by LOuroboros** [comment]
Was this tested in upcoming? Because Master currently lacks the damage refactor that SBird wrote, which affects the Metronome's held effect.

https://github.com/rh-hideout/pokeemerald-expansion/blob/master/src/battle_util.c#L9645-L9648

https://github.com/rh-hideout/pokeemerald-expansion/blob/upcoming/src/battle_util.c#L9661-L9664

**Comment by AsparagusEduardo** [comment]
#3246
