### ISSUE TITLE
Ice Spinner SoftResets Game

### ISSUE THREAD

**Issue by DenEbony** [rh-hideout/pokeemerald-expansion#3245]
### Description

https://github.com/rh-hideout/pokeemerald-expansion/assets/96850956/bcfe7d68-48f6-4055-acf6-04e63efe6445

The Move **Ice Spinner** works correctly, however after its effect, it soft resets the game as seen in the video above. The treecko is only modified to test the move out, as well as the Poochyena only being modified to test Ice Spinner's functionality.

### Version

1.5.2 (Default)

### Discord contact info

@denebony

**Comment by LOuroboros** [comment]
Can confirm on both, Master and Upcoming.

Sometimes it just freezes the game instead of provoking a hard crash, weirdly enough.

**Comment by AlexOn1ine** [comment]
Technically I have a fix for the crash but there is a string issue I struggle to fix alongside. It prints that a misty terrain was set instead of terrain ending but I have an other idea that I'll try tomorrow. If that doesn't work I'll either pr the fix or post it here and hopefully someone fixes the string issue 😅

**Comment by LOuroboros** [comment]
From what I could see, the issue is specifically caused by the `gBattleCommunication[MULTISTRING_CHOOSER] = 4;` in the `case EFFECT_HIT_SET_REMOVE_TERRAIN` of `HandleTerrainMove`, for whatever that's worth.

The moment you remove that from the code, the effect goes on like normal, but the text string is naturally incorrect as `gBattleCommunication` is what handles choosing the right one.

Also, this may not be necessary, but I think that chunk is missing a `gFieldTimers.terrainTimer = 0;`?
