### ISSUE TITLE
Moves with EFFECT_ATTACK_UP_USER_ALLY theorically can always be blocked by ally's Soundproof

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#3702]
### Description

It should check the `soundMove` flag.

### Version

upcoming (Edge)

### Upcoming Version

95bdc9a1359b1c9df09eae84f0f566fda646b296

### Discord contact info

AsparagusEduardo

**Comment by AlexOn1ine** [comment]
I think it would be better to add a new target bit like `TARGET_USER_SIDE` instead of fixing it in patches. This one could be solved with a callnative but I don't think it's optimal because we might get problems like that in the future if moves target both the user and ally. 

Though tbh I'm not really open to doing this myself 😅
