### ISSUE TITLE
Menu item icon is cut off by darkness

### ISSUE THREAD

**Issue by Ninjdai1** [rh-hideout/pokeemerald-expansion#3795]
### Description

Debug menu's item icons are cut off by darkness
![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/65647523/3688cd53-0574-4f9d-a41d-73bd08a636ed)
![pokeemerald-1](https://github.com/rh-hideout/pokeemerald-expansion/assets/65647523/1c99bb82-7e78-40d0-87ca-6db9bd41f4cb)

### Version

Upcoming

### Upcoming Version

2af6d65893dbd37c1f370f3d71ef1c7a73a3e840

### Discord contact info

@ninjdai

**Comment by hedara90** [comment]
Looking into this issue, is it something that needs to be solved?
And is it something that can be solved (easily)?
The sprite for the icon in the debug menu would need to be drawn above the `scanlineeffect` that creates the "darkness", is that possible to do without major reworks?
Overall it's a cosmetic issue that won't affect players, since it affect the debug menu only, and it only occludes the sprite, the text still works and it only happens in areas with the darkness effect.

**Comment by AlexOn1ine** [comment]
Looking into this issue, is it something that needs to be solved?
I don't think that we need to solve this

**Comment by hedara90** [comment]
Closing then
