### ISSUE TITLE
Prof. Birch cannot identify Pokedex correctly

### ISSUE THREAD

**Issue by katykat5099** [rh-hideout/pokeemerald-expansion#3874]
### Description

If you set the entire pokedex completed in the debug menu and talk to Birch to evaluate the pokedex, or encounter him in any other situation where he checks your progress, he will not identify that you have completed the pokedex in any way.
Maybe related to the regional dex originally being a higher number?

![profbirchdialogpokedex](https://github.com/rh-hideout/pokeemerald-expansion/assets/12654608/b8636c96-6933-478d-9a14-5e59aaf639ea)

### Version

1.7.1 (Default)

### Upcoming Version

515aa367bfeb542e1cfa888ebf4b86351e9946e9

### Discord contact info

kakarikiki

**Comment by LOuroboros** [comment]
I think the cause is just the weird way in which the function that handles the logic for the rating message is written, in other words, `GetPokedexRatingText`.

**Comment by Bassoonian** [comment]
I think there's two possible options here: leave it as is because part of that code needs special handling for whichever mythical you have in your regional dex, or have the `count < x` scale dynamically based on the size of the dex. RSE has `200 + 2` (with a message for every `200 / 20` + completion), ORAS has `209 + 2` (thanks GF) so we could do `209 / 20` + completion with the necessary rounding shenanigans for these kind of issues, I suppose. If we don't magic number the `+2`, we could perhaps make a table with mythicals that aren't included in the count for completion and include that table size in the formula.

**Comment by LOuroboros** [comment]
> or have the `count < x` scale dynamically based on the size of the dex. 

> we could perhaps make a table with mythicals that aren't included in the count for completion (`{ SPECIES_JIRACHI, SPECIES_DEOXYS }`) and include that table size in the formula.

I like that :eyes:
