### ISSUE TITLE
Add in game warning for incompatible emulators

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#4119]
### Description

Conversation started here: https://discord.com/channels/419213663107416084/774393519569502268/1203059551956635649

My Proposed solutions here: https://discord.com/channels/419213663107416084/774393519569502268/1203061530506297354

This issue is for 3️⃣. The PR that resolves this issue should

1. detect if the player is using a "blessed" emulator
2. If not, display a warning before the RHH Egg introduction that requires a button press to proceed
3. Allow developers to disable this warning via a config

### Discord contact info

pkmnsnfrn

**Comment by DizzyEggg** [comment]
My opinion may be a bit controversial on this subject, but I think that we should _not_ do that. At least, not now.

IIRC so far there have been only 2 instances of confirmed emulator inaccuracies. 
First in Intro #2664 for VBA and John Lite emulators which was a trivial one-line fix. 
Second, very recently with emulators crashing because of division by zero in move animations. Which again, was easy to fix and an UB in the first place. #4121

I know there are legit causes of some emulators like VBA actually not working, but imo until we have an occurrence confirmed on Expansion there's no need for the warning. 

Another thing which I kind of worry about it is that if someone encounters a real bug on a bad emu, it'll be dismissed as emu's fault which may not necessarily be true.

**Comment by pkmnsnfrn** [comment]
> I know there are legit causes of some emulators like VBA actually not working, but imo until we have an occurrence confirmed on Expansion there's no need for the warning.

I would be very surprised if there were **no** other instances of a "bad" emu breaking expansion, but if it is, then I will concede this point. Do you agree that once we have a real, reproduceable, emulator problem, that this would become a priority?

> Another thing which I kind of worry about it is that if someone encounters a real bug on a bad emu, it'll be dismissed as emu's fault which may not necessarily be true.

I think that's fair, but I also think that's already a problem. Think about how many bugs from end users that don't even make it past the dev because the dev assumed a bad emu or cheats. I don't think the presence of this screen actually changes the number of reported bugs in either direction.

**Comment by AlexOn1ine** [comment]
In fairness I was one who was doubting that there are issues in the code because one emu crashed on certain stuff but I was proven wrong by Egg when he found out the problems and now I agree. If it's possible to detect more issues through bad emulators it's an upside, not downside.

**Comment by DizzyEggg** [comment]
> I would be very surprised if there were **no** other instances of a "bad" emu breaking expansion, but if it is, then I will concede this point. Do you agree that once we have a real, reproduceable, emulator problem, that this would become a priority?

Sure, if we have a case like this then I'm all for the warning screen.

**Comment by pkmnsnfrn** [comment]
Fair. I'll close this for now, since Github doesn't seem to have a "draft" variant for issues.
