### ISSUE TITLE
G-Max Volt Crash ignores Volt Absorb

### ISSUE THREAD

**Issue by WillKolada** [rh-hideout/pokeemerald-expansion#4478]
### Description

In a single battle, a Gigantamax Pikachu used G-Max Volt Crash against a Volt Absorb Kilowattrel. Instead of absorbing the hit, the Kilowattrel took damage. There was no ability suppression such as Mold Breaker or Gastro Acid involved.

Though I haven't tested further, it's possible this bug applies to other Electric immunity abilities like Lightning Rod and Motor Drive. It may also apply to other G-Max/Max Moves and other immunity abilities, like G-Max Wildfire ignoring Flash Fire.

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

d2330a01cf9715a4bd258b82cdc08390c76af87e

### Discord contact info

Special K#8400

**Comment by hedara90** [comment]
Tested with:
Volt Absorb, Lightning Rod, Motor Drive, Flash Fire, Water Absorb, Storm Drain.
In all cases the attacks bypass the absorption effect when Dynamaxed, but redirection effects still work in double battles, but the pokemon that the move is redirection to takes damage instead of the stat increasing effect.
