### ISSUE TITLE
New flag for pokemon in trainer_parties 

### ISSUE THREAD

**Issue by ShadowzLmao2** [rh-hideout/pokeemerald-expansion#4749]
### Description

it would be nice if there was some sort of flag like .shouldDynamax but for switching into predesignated mons when certain conditions are met like for example trick room being up. there might be a team where some mons but not all want trick room
It could be something like .trickRoomMon = true, or something like that

### Discord contact info

SShadowzLmao#3643

**Comment by AlexOn1ine** [comment]
This is something a user should take care by themselves because it is highly subjective and the expansion would never stop making flags like that. It would simply explode because there are tons of situations like that.

For trickroom I highly suggest using the `AI_FLAG_POWERFUL_STATUS` and building your team around it.

**Comment by AlexOn1ine** [comment]
If someone has an idea how we could handle it without exploding please. If there is a good idea I'll reopen.
