### ISSUE TITLE
Terastalisation changes Pokémon sprites to their female variants

### ISSUE THREAD

**Issue by Bassoonian** [rh-hideout/pokeemerald-expansion#4961]
### Description

![teraspriteissue](https://github.com/user-attachments/assets/b47c01a3-9369-40da-9a7a-7b6dbf55ac40)

### Version

upcoming (Edge)

**Comment by kittenchilly** [comment]
Oh, this is likely due to the AnimTask_TransformMon, which I also run even if the mon doesn't change so we don't have to duplicate scripts. I wonder if this always happens with that AnimTask, we just never noticed it since a form change has never had a gender difference in its sprite.

**Comment by iriv24** [comment]
I followed `AnimTask_TransformMon` down to the call to `HandleLoadSpecialPokePic` on line 929 of `src\battle_gfx_sfx_util.c`, which seems to be where something is going wrong. I replaced the last parameter to that function call (currently its `gTransformedPersonalities[battlerAtk]`) with `personalityValue` that gets set on the lines above it and that fixed the issue mentioned here, but I don't have a full understanding of all the places that call this code or really what `gTransformedPersonalities[battlerAtk]` even is, so I am not confident that this wouldn't break some other form change behavior elsewhere, which is why I haven't opened a PR yet. Mostly just adding this comment so someone who has a better understanding of this code can see it

**Comment by Bassoonian** [comment]
Fixed by #4975
