### ISSUE TITLE
Battle Factory Swap Returns No Pokemon

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#5082]
### Description

1. Enter the Battle Tent in Slateport City, and win the first battle
2. Attempt to swap Pokemon
3. Expected to see last enemy's party, instead we see ???

This was broken by 41583673a5.
the commit before it, 81bd14818e does not have this problem.

### Video
https://github.com/user-attachments/assets/1c94a7cc-41e6-49ca-ad5b-f905e5be4b87

### Version

upcoming (Edge)

### Upcoming/master Version

346b29ff678159a27366454a28f6cb3c4daf3e22

### Discord contact info

psf

**Comment by pkmnsnfrn** [comment]
@ghoulslash 
@AlexOn1ine 

Discord convo: https://discord.com/channels/419213663107416084/774393519569502268/1269157496468275210

Open to any ideas on how to address

**Comment by SarnPoke** [comment]
Adding this here cause the OG comment doesn't mention it. But the Battle Factory Swap can also break in another way by doing this:
1. Win a battle in the Battle Tent/Factory.
2. Choose "REST".
3. After game reload, choose "GO ON".
4. All of player's mons will now be "??????????" and enemy's party from last battle is preserved.

Video:

https://github.com/user-attachments/assets/6b2f28f8-61bd-43d0-860c-2b3a08f746e7

**This** bug is not fixed by reverting #4867, unlike the main one mentioned in the OG comment.
