### ISSUE TITLE
AI Flag to prioritize first move slot

### ISSUE THREAD

**Issue by pkmnsnfrn** [rh-hideout/pokeemerald-expansion#5226]
### Description

# `LEAD_POKEMON_FIRST_MOVE_AT_START`

> Unless affected by `CHECK_BAD_MOVE`, use the first move the lead Pokémon has on the first turn. Allows the use of moves like Parting Shot, Roar, Double Team, Splash, Draco Meteor, etc, when the lead has other moves that normally would be equal or grater score.

### Discord contact info

TrainerX493

**Comment by Pawkkie** [comment]
This was discussed pretty extensively on Discord in the Battle AI Flags Poll thread starting [here](https://discord.com/channels/419213663107416084/1266027326882185248/1283622702686535681), and we determined that after clarifying the details of exactly how this would work, it's niche enough that it's likely better served by just using the dynamic trainer AI flags ghoul recently added for specific cases as needed, rather than writing a full flag for expansion. 

I think we all forgot to close this after that discussion finished lol
