### ISSUE TITLE
ASSUMPTIONS block doesn't work after removing fno-toplevel-reorder

### ISSUE THREAD

**Issue by AsparagusEduardo** [rh-hideout/pokeemerald-expansion#5865]
### Description

![image](https://github.com/user-attachments/assets/585cd6cf-34b2-4243-9be5-74b9d3760ae1)
Before:
![image](https://github.com/user-attachments/assets/2fadc6cd-6315-4dec-9d5e-f9a4936f7040)

### Version

upcoming (Edge)

### Upcoming/master Version

6a2a3b254091a0766cce7432ad775ae372f5f9a5

### Discord contact info

AsparagusEduardo

**Comment by mrgriffin** [comment]
Ah, because the test runner expects the `ASSUMPIONS` block to be linked before the other tests in the file. [Check for assumptions runner](<https://github.com/rh-hideout/pokeemerald-expansion/blob/master/test/test_runner.c#L285>), then [we skip over any following tests until we reach another assumptions runner](<https://github.com/rh-hideout/pokeemerald-expansion/blob/master/test/test_runner.c#L177>).

**Comment by AlexOn1ine** [comment]
#5869
